import streamlit as dt_panel
import sqlite3
import pandas as pd
import time
import os

# DYNAMIC ROADMAP ALIGNMENT: Matches database location dynamically
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DB_PATH = os.path.join(BASE_DIR, "sovereign_metrics.db")

dt_panel.set_page_config(page_title="Sovereign Real-Time Telemetry Interface", layout="wide")
dt_panel.title("Sovereign Real-Time Telemetry Interface")
dt_panel.subheader("Industrial Edge-AI Control & Monitoring Console")

def fetch_latest_metrics():
    """Extracts the latest database logs generated by the Viper core receiver loop."""
    try:
        conn = sqlite3.connect(DB_PATH)
        cursor = conn.cursor()
        # Enable parallel read locks while receiver is writing to disk
        cursor.execute("PRAGMA journal_mode=WAL;")
        df = pd.read_sql_query("""
            SELECT timestamp_epoch, sequence_id, node_state, target_status, pwm_output 
            FROM system_logs 
            ORDER BY id DESC LIMIT 50
        """, conn)
        conn.close()
        return df.iloc[::-1]
    except Exception:
        # Fallback empty structural frame ensuring safe frontend rendering
        return pd.DataFrame(columns=["timestamp_epoch", "sequence_id", "node_state", "target_status", "pwm_output"])

# Continuous visual matrix refresh track
placeholder = dt_panel.empty()

while True:
    df = fetch_latest_metrics()
    
    with placeholder.container():
        if df.empty or len(df) == 0:
            dt_panel.warning("Awaiting live stream initiation from the v13.0-EXTREME Viper Core...")
        else:
            col1, col2, col3 = dt_panel.columns(3)
            latest = df.iloc[-1]
            
            with col1:
                dt_panel.metric(label="Sequence ID", value=f"#{int(latest['sequence_id'])}")
            with col2:
                dt_panel.metric(label="Active Node State", value=str(latest['node_state']))
            with col3:
                dt_panel.metric(label="Target Status / PWM", value=f"{latest['target_status']} ({latest['pwm_output']:.2f}V)")
            
            dt_panel.subheader("Live Operational Waveform Telemetry")
            chart_data = df.copy()
            chart_data = chart_data.set_index("sequence_id")
            dt_panel.line_chart(chart_data[["pwm_output"]])
            
            dt_panel.subheader("System Data Ledger (Last 10 Packets)")
            dt_panel.dataframe(df.tail(10), use_container_width=True)
            
    dt_panel.rerun()