import streamlit as st
import sqlite3
import pandas as pd
import time

# ==========================================
# COMMERCIAL LICENSED DASHBOARD FRONT-END
# ==========================================
st.set_page_config(page_title="Sovereign Telemetry Matrix", layout="wide")

st.title("⚓ Sovereign Real-Time Telemetry Interface")
st.subheader("Industrial Edge-AI Control & Monitoring Console")

DB_PATH = "sovereign_metrics.db"

def fetch_latest_metrics():
    """Extracts the latest database logs generated by the Viper core receiver loop."""
    try:
        conn = sqlite3.connect(DB_PATH)
        df = pd.read_sql_query("""
            SELECT timestamp_epoch, sequence_id, node_state, target_status, pwm_output 
            FROM system_logs 
            ORDER BY id DESC LIMIT 50
        """, conn)
        conn.close()
        return df.iloc[::-1] # Reverse dataframe so time flows left-to-right
    except Exception:
        # Fallback empty structure if the database is initializing
        return pd.DataFrame(columns=["timestamp_epoch", "sequence_id", "node_state", "target_status", "pwm_output"])

# Initialize Live Dashboard Dynamic View
df_live = fetch_latest_metrics()

if not df_live.empty:
    latest_row = df_live.iloc[-1]
    
    # 1. Top-Tier Executive Status Dials
    col1, col2, col3 = st.columns(3)
    with col1:
        st.metric(label="Active Node State", value=str(latest_row["node_state"]))
    with col2:
        st.metric(label="Target Analytics Status", value=str(latest_row["target_status"]))
    with col3:
        st.metric(label="Hardware PWM Output Force", value=f"{float(latest_row['pwm_output']):.2f}")
        
    st.markdown("---")
    
    # 2. Real-Time Graphical Analytical Engine
    st.subheader("Live Operational Waveform Telemetry")
    st.line_chart(data=df_live, x="sequence_id", y="pwm_output")
    
    # 3. Live System Event Log Dataframe
    st.subheader("System Event Log (API Ready)")
    st.dataframe(df_live.tail(10), use_container_width=True)
else:
    st.info("Awaiting live stream initiation from the v13.0-EXTREME Viper Core...")

# Auto-refresh loop mechanism to keep the dashboard streaming
time.sleep(1)
st.rerun()
